spring.application.name=student-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Eguasco@79
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Google Login
spring.security.oauth2.client.registration.google.client-id=565041465589-4gbolpcalh0millkte1ibbpb23vtbq4k.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

#logging
logging.level.org.springframework.security=TRACE
logging.level.org.hibernate.SQL=DEBUG


#Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect